services:

  dabo-bot:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
  
  dabo-ohlcv-candles-indicators-5m:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /dabo/fetch-ohlcv-candles-indicators.sh 5m 301


  dabo-ohlcv-candles-indicators-15m:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /dabo/fetch-ohlcv-candles-indicators.sh 15m 901


  dabo-ohlcv-candles-indicators-1h:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /dabo/fetch-ohlcv-candles-indicators.sh 1h 3601


  dabo-ohlcv-candles-indicators-4h:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /dabo/fetch-ohlcv-candles-indicators.sh 4h 3720


  dabo-ohlcv-candles-indicators-1d:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /dabo/fetch-ohlcv-candles-indicators.sh 1d


  dabo-ohlcv-candles-indicators-1w:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro  
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /dabo/fetch-ohlcv-candles-indicators.sh 1w


  dabo-calc-indicators-hist:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /dabo/calc-indicators-hist.sh
    cpu_shares: 128
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M

  dabo-transaction-history:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /dabo/fetch-transaction-history.sh
    cpu_shares: 128
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  dabo-fetch-coinmarketcapids:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /dabo/fetch-coinmarketcapids.sh
    cpu_shares: 128
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  dabo-webpage:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /dabo/create_webpage.sh
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M

  dabo-web:
    image: nginx:latest
    restart: unless-stopped
    networks:
      - dabo--network
    volumes:
      - ./data:/usr/share/nginx/html:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M

networks:
  dabo--network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-dabo


