services:

  dabo-bot:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
    entrypoint: >
      /bin/bash -lc
      "mkdir -p /dabo/htdocs/botdata/logs ; /dabo/dabo-bot.sh 2>&1 | tee -a /dabo/htdocs/botdata/logs/dabo-bot.log"
 
  dabo-ohlcv-candles-indicators-5m:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: >
      /bin/bash -lc
      "mkdir -p /dabo/htdocs/botdata/logs ; /dabo/fetch-ohlcv-candles-indicators.sh 5m 301 2>&1 | tee -a /dabo/htdocs/botdata/logs/dabo-bot.5m.log"


  dabo-ohlcv-candles-indicators-15m:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: >
      /bin/bash -lc
      "mkdir -p /dabo/htdocs/botdata/logs ; /dabo/fetch-ohlcv-candles-indicators.sh 15m 901 2>&1 | tee -a /dabo/htdocs/botdata/logs/fetch-ohlcv-candles-indicators.15m.log"


  dabo-ohlcv-candles-indicators-1h:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: >
      /bin/bash -lc
      "mkdir -p /dabo/htdocs/botdata/logs ; /dabo/fetch-ohlcv-candles-indicators.sh 1h 3601 2>&1 | tee -a /dabo/htdocs/botdata/logs/fetch-ohlcv-candles-indicators.1h.log"


  dabo-ohlcv-candles-indicators-4h:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: >
      /bin/bash -lc
      "mkdir -p /dabo/htdocs/botdata/logs ; /dabo/fetch-ohlcv-candles-indicators.sh 4h 3720 2>&1 | tee -a /dabo/htdocs/botdata/logs/fetch-ohlcv-candles-indicators.4h.log" 


  dabo-ohlcv-candles-indicators-1d:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: >
      /bin/bash -lc
      "mkdir -p /dabo/htdocs/botdata/logs ; /dabo/fetch-ohlcv-candles-indicators.sh 1d 2>&1 | tee -a /dabo/htdocs/botdata/logs/fetch-ohlcv-candles-indicators.1d.log"


  dabo-ohlcv-candles-indicators-1w:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro  
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: >
      /bin/bash -lc
      "mkdir -p /dabo/htdocs/botdata/logs ; /dabo/fetch-ohlcv-candles-indicators.sh 1w 2>&1 | tee -a /dabo/htdocs/botdata/logs/fetch-ohlcv-candles-indicators.1w.log"


  dabo-calc-indicators-hist:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: >
      /bin/bash -lc
      "mkdir -p /dabo/htdocs/botdata/logs ; /dabo/calc-indicators-hist.sh 2>&1 | tee -a /dabo/htdocs/botdata/logs/calc-indicators-hist.log"
    cpu_shares: 128
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M


  dabo-transaction-history:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./secrets:/dabo/secrets:ro
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: >
      /bin/bash -lc
      "mkdir -p /dabo/htdocs/botdata/logs ; /dabo/fetch-transaction-history.sh 2>&1 | tee -a /dabo/htdocs/botdata/logs/fetch-transaction-history.log"
    cpu_shares: 128
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M


  dabo-fetch-coinmarketcapids:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: >
      /bin/bash -lc
      "mkdir -p /dabo/htdocs/botdata/logs ; /dabo/fetch-coinmarketcapids.sh 2>&1 | tee -a /dabo/htdocs/botdata/logs/fetch-coinmarketcapids.log"
    cpu_shares: 128
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M


  dabo-webpage:
    image: ghcr.io/egabosh/dabo
    restart: unless-stopped
    networks:
      - dabo--network
    user: 10000:10000
    volumes:
      - ./strategies:/dabo/strategies:ro
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
      - ./data:/dabo/htdocs:rw
      - ./home:/dabo/home:rw
      - ./notify.local.conf:/usr/local/etc/notify.conf:ro
      - /etc/localtime:/etc/localtime:ro
    entrypoint: >
      /bin/bash -lc
      "mkdir -p /dabo/htdocs/botdata/logs ; /dabo/create_webpage.sh 2>&1 | tee -a /dabo/htdocs/botdata/logs/create_webpage.log"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M


  dabo-web:
    image: nginx:latest
    restart: unless-stopped
    networks:
      - dabo--network
    volumes:
      - ./data:/usr/share/nginx/html:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M


  dabo-django:
    build:
      context: .
      dockerfile: Dockerfile-django
    volumes:
      - ./data-django:/app
      - ./data:/dabo/htdocs:ro
      - ./secrets_django:/dabo/secrets:rw
      - ./strategies:/dabo/strategies:rw
      - ./dabo-bot.conf:/dabo/dabo-bot.override.conf
    environment:
      - PYTHONUNBUFFERED=1


networks:
  dabo--network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-dabo


