# Dockerfile-django
FROM python:3-slim
# metadata
ARG VERSION
ENV VERSION=${VERSION}
ARG BUILD_DATE
ENV BUILD_DATE=${BUILD_DATE}
ARG DESCRIPTION
ENV DESCRIPTION=${DESCRIPTION}
LABEL org.opencontainers.image.source="https://github.com/egabosh/dabo" \
      org.opencontainers.image.description=$DESCRIPTION \
      org.opencontainers.image.version=$VERSION \
      org.opencontainers.image.authors="Oliver Bohlen (aka olli/egabosh)" \
      org.opencontainers.image.licenses="GPL-3.0 (for dabo-bot in /dabo)" \
      org.opencontainers.image.created=$BUILD_DATE \
      org.opencontainers.image.vendor="egabosh" \
      org.opencontainers.image.documentation="https://github.com/egabosh/dabo#readme" \
      org.opencontainers.image.base.name="Debian Linux" \
      org.opencontainers.image.base.licenses="Various, see https://www.debian.org/legal/licenses/"

WORKDIR /app/dabo-webui

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl wget \
 && rm -rf /var/lib/apt/lists/*

# Bootstrap & Lightweight Charts herunterladen
RUN mkdir -p /app/dabo-webui/main/static/css && \
    mkdir -p /app/dabo-webui/main/static/js && \
     wget -O /app/dabo-webui/main/static/css/bootstrap.min.css https://cdn.jsdelivr.net/npm/bootstrap@5/dist/css/bootstrap.min.css && \
     wget -O /app/dabo-webui/main/static/js/bootstrap.bundle.min.js https://cdn.jsdelivr.net/npm/bootstrap@5/dist/js/bootstrap.bundle.min.js && \
     wget -O  /app/dabo-webui/main/static/js/lightweight-charts.standalone.production.js https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js

#    curl -o /app/dabo-webui/main/static/css/bootstrap.min.css \
#         https://cdn.jsdelivr.net/npm/bootstrap@5/dist/css/bootstrap.min.css && \
#    curl -o /app/dabo-webui/main/static/js/bootstrap.bundle.min.js \
#         https://cdn.jsdelivr.net/npm/bootstrap@5/dist/js/bootstrap.bundle.min.js && \
#    curl -o /app/dabo-webui/main/static/js/lightweight-charts.standalone.production.js \
#         https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js

RUN pip install --no-cache-dir django gunicorn uvicorn whitenoise

ENTRYPOINT ["gunicorn", "dabo_webui.asgi:application", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:80"]

