FROM debian:latest
LABEL org.opencontainers.image.source="https://github.com/egabosh/dabo"
# basics
RUN apt-get update && \
  apt-get -y install curl && \
  curl -L https://github.com/egabosh/linux-setups/raw/refs/heads/main/debian/docker/build-debian-env.sh >build-debian-env.sh && \
  bash -ex build-debian-env.sh
# dabo
COPY ./dabo /dabo
WORKDIR /python-dabo
# python
RUN python3 -m venv /python-dabo
ENV PATH="/python-dabo/bin:$PATH"
# ccxt and ai stuff
RUN pip install --upgrade pip && \
  pip install ccxt tensorflow[and-cuda] pandas scikit-learn
# defaults
RUN addgroup --system --gid 10000 dabo
RUN adduser --system --disabled-password --disabled-login --gid 10000 --uid 10000 --home /dabo/home dabo
ENV LANG en_US.utf8
WORKDIR /dabo/htdocs/botdata
ENTRYPOINT ["/dabo/dabo-bot.sh"]
